# Based on wp-library _secret.yaml template

{{- if and .Values.secrets .Values.secrets.data (not (empty .Values.secrets.data)) }}
{{- range .Values.secrets.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .name $ }}
  {{- if and .namespace (not (empty .namespace)) }}
  namespace: {{ tpl .namespace $ }}
  {{- end }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .type | default "Opaque" }}

# Base64 encoded data
{{- if .data }}
data:
  {{- range $key, $val := .data }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
{{- end }}

# Plain data
{{- if .stringData }}
stringData:
  {{- range $key, $val := .stringData }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
